import {
  Body,
  Controller,
  Get,
  HttpCode,
  Param,
  Patch,
  Post,
  Query,
} from '@nestjs/common';
import { CurrentUser } from '../../../common/decorators/current-user.decorator';
import { AuthenticatedUser } from '../../auth/jwt.strategy';
import { validateRow } from '../import/domain/validate';
import { ImportField } from '../import/domain/fields';
import { LicensesService } from './licenses.service';
import { RemindersService } from '../reminders/reminders.service';
import {
  CreateLicenseDto,
  ListLicensesQueryDto,
  UpdateLicenseDto,
} from './dto/license.dto';

/**
 * Licences API.
 *
 * Tenant comes from the JWT on every route. There is no DELETE: licences are
 * archived, never removed, because compliance records are evidence.
 */
@Controller('licenses')
export class LicensesController {
  constructor(
    private readonly licensesService: LicensesService,
    private readonly remindersService: RemindersService,
  ) {}

  /**
   * Validate one licence's free-text fields WITHOUT writing anything.
   *
   * WHY THIS EXISTS RATHER THAN A SECOND VALIDATOR
   * ---------------------------------------------
   * The single-licence form is a one-row import. Slice 10 already built the
   * validator for that row — `validateRow` is pure, takes the same
   * `Partial<Record<ImportField, string>>` shape, and is tested against
   * ambiguous dates, impossible calendar dates, reversed date order and
   * malformed emails.
   *
   * Writing date parsing a second time in the browser would give the form
   * different messages from import for the same input, and the two would
   * drift. So the form asks the server the same question import asks, gets
   * the same answers, and gets back the PARSED dates so it can echo them to
   * the user unambiguously before anything is written.
   *
   * `@IsPlainDate()` on CreateLicenseDto is still the authority at commit —
   * this endpoint cannot be relied on, only believed. It exists for the
   * message quality, not for safety.
   *
   * Pure: no database access, no writes, nothing logged.
   */
  @Post('check')
  @HttpCode(200)
  check(@Body() body: { values?: Partial<Record<ImportField, string>> }) {
    return validateRow(1, body.values ?? {});
  }

  @Post()
  create(
    @CurrentUser() user: AuthenticatedUser,
    @Body() dto: CreateLicenseDto,
  ) {
    return this.licensesService.create(user.tenantId, user.id, dto);
  }

  @Get()
  findAll(
    @CurrentUser() user: AuthenticatedUser,
    @Query() query: ListLicensesQueryDto,
  ) {
    return this.licensesService.findAll(user.tenantId, query);
  }

  @Get(':id')
  findOne(@CurrentUser() user: AuthenticatedUser, @Param('id') id: string) {
    return this.licensesService.findOne(user.tenantId, id);
  }

  @Patch(':id')
  update(
    @CurrentUser() user: AuthenticatedUser,
    @Param('id') id: string,
    @Body() dto: UpdateLicenseDto,
  ) {
    return this.licensesService.update(user.tenantId, user.id, id, dto);
  }

  /**
   * The persisted reminder timeline for one licence.
   *
   * Read-only. Obligations are generated by the licence lifecycle, never by a
   * caller — there is deliberately no endpoint to create or fire a reminder.
   */
  @Get(':id/reminders')
  async findReminders(
    @CurrentUser() user: AuthenticatedUser,
    @Param('id') id: string,
  ) {
    // Proves the licence belongs to the caller's tenant before returning
    // anything hanging off it; throws 404 otherwise.
    await this.licensesService.findOne(user.tenantId, id);
    return this.remindersService.findForLicense(user.tenantId, id);
  }

  @Post(':id/archive')
  @HttpCode(200)
  archive(@CurrentUser() user: AuthenticatedUser, @Param('id') id: string) {
    return this.licensesService.archive(user.tenantId, user.id, id);
  }
}
